baseURL = 'https://boss2026.nofiat.me/'
languageCode = 'en-us'
title = 'journey through BOSS 2026'
theme = 'PaperMod'

[params]
  description = "https://bosschallenge.xyz"
  author = "jirigrill"

# Markdown settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown if needed
